package com.shenyang.bean;

public class Code {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CODE.id
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CODE.blog_id
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    private Integer blogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CODE.code
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    private String code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CODE.id
     *
     * @return the value of CODE.id
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CODE.id
     *
     * @param id the value for CODE.id
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CODE.blog_id
     *
     * @return the value of CODE.blog_id
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    public Integer getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CODE.blog_id
     *
     * @param blogId the value for CODE.blog_id
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    public void setBlogId(Integer blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CODE.code
     *
     * @return the value of CODE.code
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CODE.code
     *
     * @param code the value for CODE.code
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }
}