package com.shenyang.dao;

import com.shenyang.bean.Blog;
import com.shenyang.bean.BlogExample;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface BlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    long countByExample(BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    int deleteByExample(BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    int insert(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    int insertSelective(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    List<Blog> selectByExampleWithBLOBs(BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    List<Blog> selectByExample(BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    Blog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    int updateByExampleSelective(@Param("record") Blog record, @Param("example") BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") Blog record, @Param("example") BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    int updateByExample(@Param("record") Blog record, @Param("example") BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    int updateByPrimaryKeySelective(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    int updateByPrimaryKey(Blog record);

    /**
     * 查询指定用户最近的指定记录数的博客
     *
     * @param userId
     * @param limit
     * @return
     */
    List<Blog> queryBlogByLimit(@Param("userId") int userId, @Param("limit") int limit);

    /**
     * 查询最近指定记录数的博客
     * @param limit
     * @return
     */
    List<Blog> queryNearestBlog(@Param("limit") int limit);
}