package com.shenyang.dao;

import com.shenyang.bean.Code;
import com.shenyang.bean.CodeExample;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    long countByExample(CodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    int deleteByExample(CodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    int insert(Code record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    int insertSelective(Code record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    List<Code> selectByExampleWithBLOBs(CodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    List<Code> selectByExample(CodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    Code selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    int updateByExampleSelective(@Param("record") Code record, @Param("example") CodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") Code record, @Param("example") CodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    int updateByExample(@Param("record") Code record, @Param("example") CodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    int updateByPrimaryKeySelective(Code record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Code record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE
     *
     * @mbg.generated Sat Oct 07 12:07:57 CST 2017
     */
    int updateByPrimaryKey(Code record);

    /**
     * 批量插入代码
     *
     * @param code
     * @return
     */
    int insertCodeList(@Param("codeList") List<Code> code);
}